- platform: tado
  username: !secret tado_usr
  password: !secret tado_pwd
  home_id: 284167

- platform: tile
  username: !secret tile_usr
  password: !secret tile_pwd

- platform: tile
  username: !secret tile_usr_2
  password: !secret tile_pwd_2