### IKEA Tradfri dimmers for use with deCONZ
### The icons in the description are the icons
### shown on the actual remote for convenience

## Bedroom Jimmy's Side

# Button Middle (power icon)
- alias: 'Bedroom Jimmy IKEA button middle tap_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_slaapkamer_jim
      event: 1002
  action:
    - service_template: >
        {% if is_state('group.bedroom_ceiling', 'on') %}
          light.turn_off
        {% elif is_state('group.bedroom_ceiling', 'off') %}
          light.toggle
        {% endif %}
      entity_id: light.slaapkamer
    - service_template: >
        {% if is_state('light.slaapkamer', 'on') %}
          light.turn_on
        {% elif is_state('light.slaapkamer', 'off') %}
          light.turn_off
        {% endif %}
      entity_id: light.slaapkamer_led_lampen
    - service: light.turn_off
      entity_id:
        - light.kast_lamp
        - light.bed_lamp

# Button Left (left-arrow icon)
- alias: 'Bedroom Jimmy IKEA button left tap_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_slaapkamer_jim
      event: 4002
  action:
    service: light.toggle
    entity_id: light.nachtkastje_Jimmy

# Button Right (right-arrow icon)
- alias: 'Bedroom Jimmy IKEA button right tap_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_slaapkamer_jim
      event: 5002
  action:
    service: light.toggle
    entity_id: light.nachtkastje_jimmy

# Button Top (brightness-up icon)
- alias: 'Bedroom Jimmy IKEA button top tap_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_slaapkamer_jim
      event: 2001
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.slaapkamer
        brightness: >
          {% set bri = state_attr('light.slaapkamer', 'brightness') | int %}
          {{ [bri+30, 249] | min }}

# Button Down (brightness-down icon)
- alias: 'Bedroom Jimmy IKEA button down tap_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_slaapkamer_jim
      event: 3001
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.slaapkamer
        brightness: >
          {% set bri = state_attr('light.slaapkamer', 'brightness') | int %}
          {{ [bri-30, 0] | max }}

