### IKEA Tradfri dimmers for use with deCONZ
### The icons in the description are the icons
### shown on the actual remote for convenience

## Office Button

# Button Middle (power icon)
- alias: 'Office IKEA button middle tap_action'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: ab_kleine_kamer
        event: 1002
  action:
    - service: light.toggle
      entity_id: light.kleine_kamer
    - service: light.turn_on
      entity_id: light.computer_led

# # Button Left (left-arrow icon)
# - alias: 'Office IKEA button left tap_action'
#   initial_state: 'on'
#   trigger:
#     platform: event
#     event_type: deconz_event
#     event_data:
#       id: ab_kleine_kamer
#       event: 4002
#   action:
#     service: light.toggle
#     entity_id: light.nachtkastje_Jimmy
# 
# # Button Right (right-arrow icon)
# - alias: 'Office IKEA button right tap_action'
#   initial_state: 'on'
#   trigger:
#     platform: event
#     event_type: deconz_event
#     event_data:
#       id: ab_kleine_kamer
#       event: 5002
#   action:
#     service: light.toggle
#     entity_id: light.nachtkastje_jimmy

# Button Top (brightness-up icon)
- alias: 'Office IKEA button top tap_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_kleine_kamer
      event: 2001
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kleine_kamer
        brightness: >
          {% set bri = state_attr('light.kleine_kamer', 'brightness') | int %}
          {{ [bri+30, 249] | min }}

# Button Down (brightness-down icon)
- alias: 'Office IKEA button down tap_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_kleine_kamer
      event: 3001
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kleine_kamer
        brightness: >
          {% set bri = state_attr('light.kleine_kamer', 'brightness') | int %}
          {{ [bri-30, 0] | max }}

