- platform: template
  switches:
    xbox_one:
      value_template: "{{ is_state('media_player.xbox_one', 'on') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.xbox_one
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.xbox_one

- platform: template
  switches:
    samsung_tv:
      value_template: "{{ is_state('media_player.samsung_tv_ue65ku6000', 'on') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.samsung_tv_ue65ku6000
      turn_off:
        service: homeassistant.turn_off
        data:
          entity_id: group.samsung_tv