# BADKAMER LAMP IEDERE 10 MINUTEN UIT/AAN
- alias: badkamer_aan_uit
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.koogeek_sw_056ce9
      to: 'on'
      for:
        minutes: 10
  action:
    - service: script.turn_on
      data:
        entity_id: script.badkamer_aanuit
    - service: script.turn_off
      data:
        entity_id: script.badkamer_aanuit