# Bedroom Automations

# TURN LEDLIGHTS ON/OFF WITH TRADFRI REMOTE, BUT ONLY IF TV IS OFF
- alias: leds_off_button_press
  initial_state: 'true'
  trigger:
    platform: state
    to: 'off'
    entity_id: group.nachtkastjes
  condition:
  - condition: state
    entity_id: switch.tv_slaapkamer  
    state: 'off'
  action:
  - data:
      entity_id: light.slaapkamer_led_lampen
    service: light.turn_off

- alias: leds_on_button_press
  initial_state: 'true'
  trigger:
    platform: state
    to: 'on'
    entity_id: group.nachtkastjes
  condition:
    condition: state
    entity_id: switch.tv_slaapkamer  
    state: 'off'
  action:
  - data:
      entity_id: light.slaapkamer_led_lampen
    service: light.turn_on

# TURN SLAAPKAMER LEDLAMPEN ON AT SUNSET IF NOBODY IS HOME
- alias: leds_if_not_home
  initial_state: 'true'
  trigger:
  - platform: sun
    event: sunset
    offset: "-00:30:00"
  condition:
  - condition: state
    entity_id: group.device_status
    state: not_home
  action:
  - data:
      entity_id: light.slaapkamer_led_lampen
    service: light.turn_on

# TURN ON BEDROOM LEDS WHEN TOILETLAMP IS ON AT NIGHT
- alias: toiletlamp is vloerled
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: light.toiletlamp
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        before: '08:00:00'
        after: '00:00:00'
      - condition: state
        entity_id: switch.pc_van_jimmy
        state: 'off'
  action:
  - data:
      entity_id: script.slaapkamer_vloer_led
    service: script.turn_on