# DOORS OPEN WILL SEND ALERTS TO IOS APP (v2.0 required)
- alias: Voordeur
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.voordeur
      to: 'on'
    - platform: state
      entity_id: binary_sensor.voordeur
      to: 'off'
  action:
    - service_template: >
        {% if (is_state('device_tracker.jimmys_iphone', 'not_home')) and (is_state('device_tracker.stephanies_iphone', 'not_home'))  %}
          notify.ios_notifier
        {% elif (is_state('device_tracker.jimmys_iphone', 'home')) and (is_state('device_tracker.stephanies_iphone', 'not_home')) %}
          notify.mobile_app_iphone
        {% elif (is_state('device_tracker.jimmys_iphone', 'not_home')) and (is_state('device_tracker.stephanies_iphone', 'home')) %}
          notify.mobile_app_iphone
        {% elif (is_state('device_tracker.jimmys_iphone', 'home')) and (is_state('device_tracker.stephanies_iphone', 'home')) %}
          notify.mobile_app_iphone
        {% endif %}
      data_template:
        title: "Voordeur"
        message: >
          {% if is_state('binary_sensor.voordeur', 'on') %}
            De Voordeur is zojuist geopend!
          {% elif is_state('binary_sensor.voordeur', 'off') %}
            De Voordeur is zojuist gesloten!
          {% endif %}
        data:
          push:
            sound: >
              {% if is_state('binary_sensor.voordeur', 'on') %}
                frontdoor_opened.wav
              {% elif is_state('binary_sensor.voordeur', 'off') %}
                frontdoor_closed.wav
              {% endif %}

- alias: Woonkamer Deur
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.woonkamer_deur
      to: 'on'
    - platform: state
      entity_id: binary_sensor.woonkamer_deur
      to: 'off'
  action:
    - service_template: >
        {% if (is_state('device_tracker.jimmys_iphone', 'not_home')) and (is_state('device_tracker.stephanies_iphone', 'not_home'))  %}
          notify.ios_notifier
        {% elif (is_state('device_tracker.jimmys_iphone', 'home')) and (is_state('device_tracker.stephanies_iphone', 'not_home')) %}
          notify.mobile_app_iphone_stephanie
        {% elif (is_state('device_tracker.jimmys_iphone', 'not_home')) and (is_state('device_tracker.stephanies_iphone', 'home')) %}
          notify.mobile_app_iphone
        {% endif %}
      data_template:
        title: "Woonkamer Deur"
        message: >
          {% if is_state('binary_sensor.woonkamer_deur', 'on') %}
            De Woonkamer Deur is zojuist geopend!
          {% elif is_state('binary_sensor.woonkamer_deur', 'off') %}
            De Woonkamer Deur is zojuist gesloten!
          {% endif %}
        data:
          push:
            sound: >
              {% if is_state('binary_sensor.woonkamer_deur', 'on') %}
                livingroom_door_opened.wav
              {% elif is_state('binary_sensor.woonkamer_deur', 'off') %}
                livingroom_door_closed.wav
              {% endif %}

- alias: Slaapkamer Deur
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.slaapkamer_deur
      to: 'on'
    - platform: state
      entity_id: binary_sensor.slaapkamer_deur
      to: 'off'
  action:
    - service_template: >
        {% if (is_state('device_tracker.jimmys_iphone', 'not_home')) and (is_state('device_tracker.stephanies_iphone', 'not_home'))  %}
          notify.ios_notifier
        {% elif (is_state('device_tracker.jimmys_iphone', 'home')) and (is_state('device_tracker.stephanies_iphone', 'not_home')) %}
          notify.mobile_app_iphone_stephanie
        {% elif (is_state('device_tracker.jimmys_iphone', 'not_home')) and (is_state('device_tracker.stephanies_iphone', 'home')) %}
          notify.mobile_app_iphone
        {% endif %}
      data_template:
        title: "Slaapkamer Deur"
        message: >
          {% if is_state('binary_sensor.slaapkamer_deur', 'on') %}
            De Slaapkamer Deur is zojuist geopend!
          {% elif is_state('binary_sensor.slaapkamer_deur', 'off') %}
            De Slaapkamer Deur is zojuist gesloten!
          {% endif %}
        data:
          push:
            sound: >
              {% if is_state('binary_sensor.slaapkamer_deur', 'on') %}
                bedroom_door_opened.wav
              {% elif is_state('binary_sensor.slaapkamer_deur', 'off') %}
                bedroom_door_closed.wav
              {% endif %}
    