# RDW

# RDW Notifications for iOS
- alias: APK date expiration notification Peugeot
  initial_state: 'true'
  trigger:
    - platform: template
      value_template: "{{ ((as_timestamp(strptime(states('sensor.peugeot_207_expdate'), '%d %b %Y')) / 86400) | int) == ((as_timestamp(strptime(states('sensor.date'), '%Y-%m-%d')) / 86400) | int) + 21 }} }}"
  action:
    - service: notify.mobile_app_iphone
      data_template:
        title: 'APK Peugeot 207 SW'
        message: De APK op uw Peugeot 207 SW met kenteken 21-XX-DL verloopt op {{ states.sensor.peugeot_207_expdate.state }}. Plan een keuring bij uw garage.
        data:
          push:
            sound: default
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.apkjimz

- alias: APK date expiration notification Citroen
  initial_state: 'true'
  trigger:
    - platform: template
      value_template: "{{ ((as_timestamp(strptime(states('sensor.citroen_c1_expdate'), '%d %b %Y')) / 86400) | int) == ((as_timestamp(strptime(states('sensor.date'), '%Y-%m-%d')) / 86400) | int) + 21 }} }}"
  action:
    - service: notify.mobile_app_iphone_stephanie
      data_template:
        title: 'APK Citroën C1'
        message: De APK op uw Citroën C1 met kenteken 55-GFF-3 verloopt op {{ states.sensor.citroen_c1_expdate.state }}. Plan een keuring bij uw garage.
        data:
          push:
            sound: default
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.apksteph

# Input Booleans used for showing a notification in the frontend
- alias: APK Peugeot Boolean Reset
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.peugeot_207_expdate
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.apkjimz

- alias: APK Citroen Boolean Reset
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.citroen_c1_expdate
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.apksteph