# Update Notifications

- alias: 'Update Available Notifications'
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: updater.updater
  action:
  - service: notify.mobile_app_iphone
    data:
      title: 'Home Assistant Update'
      message: 'Er is een update voor Home Assistant uitgebracht. HA Versie {{ states.updater.updater.state }}.'
      data:
        push:
          sound: default