
# Substitutions
substitutions:
  devicename: airfryer
  upper_devicename: Airfryer
  fallback_hotspot: Airfryer Fallback
  devicename_status: Airfryer Status
  devicename_led: Airfryer Green LED

# ESPHome
esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret SSID_2
  password: !secret SSID_pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $fallback_hotspot
    password: !secret fallback_hotspot

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_pwd

ota:
  password: !secret api_pwd

# Config
binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: $devicename
  - platform: status
    name: $devicename_status

switch:
  - platform: gpio
    name: $upper_devicename
    pin: GPIO12
    id: $devicename

output:
  # Register the green LED as a dimmable output ....
  - platform: esp8266_pwm
    id: s20_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: $devicename_led
    output: s20_green_led