# Substitutions
substitutions:
  devicename: printer
  upper_devicename: Printer
  fallback_hotspot: Printer Fallback
  devicename_humidity: Kleine Kamer Luchtvochtigheid
  devicename_temperature: Kleine Kamer Temperatuur

# ESPHome
esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret SSID_2
  password: !secret SSID_pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $fallback_hotspot
    password: !secret fallback_hotspot

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_pwd

ota:
  password: !secret api_pwd

# Config
binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: $devicename

switch:
  - platform: gpio
    name: $upper_devicename
    pin: GPIO12
    id: $devicename

status_led:
  pin:
    number: GPIO13
    inverted: yes

sensor:
  - platform: dht
    model: AM2302
    pin: GPIO14
    humidity:
      name: $devicename_humidity
    temperature:
      name: $devicename_temperature
    update_interval: 10s