# Substitutions
substitutions:
  devicename: wasmachine
  upper_devicename: Wasmachine
  fallback_hotspot: Wasmachine Fallback
  devicename_current: Wasmachine Current
  devicename_voltage: Wasmachine Voltage
  devicename_power: Wasmachine Power

# ESPHome
esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret SSID_2
  password: !secret SSID_pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $fallback_hotspot
    password: !secret fallback_hotspot

captive_portal:

# Enable logging
logger:
  baud_rate: 0
  
# Enable Home Assistant API
api:
  password: !secret api_pwd

ota:
  password: !secret api_pwd

# Config
binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: $devicename

switch:
  - platform: gpio
    name: $upper_devicename
    pin: GPIO12
    id: $devicename

status_led:
  pin:
    number: GPIO13
    inverted: yes

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
    current:
      name: $devicename_current
    voltage:
      name: $devicename_voltage
    power:
      name: $devicename_power