### Philips Hue dimmers for use with deCONZ
### The icons in the description are the icons
### shown on the actual remote for convenience

## Office Remote

# Button 1 tap_action (power-on icon)
- alias: 'Office Philips button 1 tap_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_kleine_kamer_muur
      event: 1002
  action:
    service: light.turn_on
    entity_id: 
      - light.kleine_kamer
      - light.computer_led

# Button 1 hold_action (power-on icon)
- alias: 'Office Philips button 1 hold_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_kleine_kamer_muur
      event: 1001
  action:
    service: light.turn_on
    entity_id: 
      - light.computer_led

# Button 2 tap_action (brightness-up icon)
- alias: 'Office Philips button 2 tap_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_kleine_kamer_muur
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kleine_kamer
        brightness: >
          {% set bri = state_attr('light.kleine_kamer', 'brightness') | int %}
          {{ [bri+30, 249] | min }}

# Button 2 hold_action (brightness-up icon)
- alias: 'Office Philips button 2 hold_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_kleine_kamer_muur
      event: 2001
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kleine_kamer
        brightness: >
          {% set bri = state_attr('light.kleine_kamer', 'brightness') | int %}
          {{ [bri+30, 249] | min }}

# Button 2 hold_and_release_action (brightness-up icon)
- alias: 'Office Philips button 2 hold_and_release_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_kleine_kamer_muur
      event: 2003
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kleine_kamer
        brightness: >
          {% set bri = state_attr('light.kleine_kamer', 'brightness') | int %}
          {{ [bri+30, 249] | min }}

# Button 3 tap_action (brightness-down icon)
- alias: 'Office Philips button 3 tap_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_kleine_kamer_muur
      event: 3002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kleine_kamer
        brightness: >
          {% set bri = state_attr('light.kleine_kamer', 'brightness') | int %}
          {{ [bri-30, 0] | max }}

# Button 3 hold_action (brightness-down icon)
- alias: 'Office Philips button 3 hold_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_kleine_kamer_muur
      event: 3001
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kleine_kamer
        brightness: >
          {% set bri = state_attr('light.kleine_kamer', 'brightness') | int %}
          {{ [bri-30, 0] | max }}

# Button 3 hold_and_release_action (brightness-down icon)
- alias: 'Office Philips button 3 hold_and_release_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_kleine_kamer_muur
      event: 3003
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.kleine_kamer
        brightness: >
          {% set bri = state_attr('light.kleine_kamer', 'brightness') | int %}
          {{ [bri-30, 0] | max }}

# Button 4 tap_action (power-off icon)
- alias: 'Office Philips button 4 tap_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_kleine_kamer_muur
      event: 4002
  action:
    service: light.turn_off
    entity_id: 
      - light.kleine_kamer

# Button 4 hold_action (power-off icon)
- alias: 'Office Philips button 4 hold_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_kleine_kamer_muur
      event: 4001
  action:
    service: light.turn_off
    entity_id: 
      - light.computer_led
